const projectData = [
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  // {
  //   year: "2023",
  //   project: "ECommerce Website",
  //   madeAt: "Semicolon",
  //   builtWith: ["React", "Tailwind Css", "Mui"],
  //   link: "https://github.com/masud-pervez",
  // },
  // {
  //   year: "2023",
  //   project: "ECommerce Website",
  //   madeAt: "Semicolon",
  //   builtWith: ["React", "Tailwind Css", "Mui"],
  //   link: "https://github.com/masud-pervez",
  // },
  // {
  //   year: "2023",
  //   project: "ECommerce Website",
  //   madeAt: "Semicolon",
  //   builtWith: ["React", "Tailwind Css", "Mui"],
  //   link: "https://github.com/masud-pervez",
  // },
  // {
  //   year: "2023",
  //   project: "ECommerce Website",
  //   madeAt: "Semicolon",
  //   builtWith: ["React", "Tailwind Css", "Mui"],
  //   link: "https://github.com/masud-pervez",
  // },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
  {
    year: "2023",
    project: "ECommerce Website",
    madeAt: "Semicolon",
    builtWith: ["React", "Tailwind Css", "Mui"],
    link: "https://github.com/masud-pervez",
  },
];

export default projectData;
